config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'recipes#index'
  resources :recipes do
    resources :ingredients
    resources :tags
  end

  resources :ingredients do
    resources :recipes
  end

  resources :tags do
    resources :recipes
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord

  validates :name, presence: true
  has_many :ingredient_recipes
  has_many :recipes, :through => :ingredient_recipes
  # scope :add_to_recipe, -> (recipe) {"  ", "#{recipe.downcase}" }
  
end

app/models/ingredient_recipe.rb
class IngredientRecipe < ApplicationRecord
  belongs_to :ingredient
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  
  scope :five_star, -> { where(rating: 5).limit(5) }
  scope :search, -> (name_parameter) { where("LOWER(name) like ?", "%#{name_parameter.downcase}%") }
  
  validates :name, presence: true
  has_many :ingredient_recipes
  has_many :ingredients, :through => :ingredient_recipes

  has_many :recipe_tags
  has_many :tags, :through => :recipe_tags
end

# if params[:name_search]
# upcase_results = Recipe.search(params[:name_search].capitalize)
# downcase_results = Recipe.search(params[:name_search].downcase)
# @results = upcase_results + downcase_results
# @search = true
# render :index

app/models/recipe_tag.rb
class RecipeTag < ApplicationRecord
  belongs_to :recipe
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, presence: true
  has_many :recipe_tags
  has_many :recipes, :through => :recipe_tags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  def index
    @ingredients = Ingredient.all
    render :index
  end

  def new
    if params[:recipe_id]
      @recipe = Recipe.find(params[:recipe_id])
      @ingredient = @recipe.ingredients.new
    else
      @ingredient = Ingredient.new
    end
    render :new
  end

  def create
    if params[:recipe_id]
      @recipe = Recipe.find(params[:recipe_id])
      @ingredient = @recipe.ingredients.new(ingredient_params)
      if @ingredient.save
        @recipe.ingredients << @ingredient
        puts @recipe.ingredients
        flash[:notice] = "Ingredient successfully added!"
        redirect_to recipe_path(@recipe)
      else
        render :new
      end
    else
      @ingredient = Ingredient.create(ingredient_params)
      if @ingredient.save
        flash[:notice] = "Ingredient successfully added!"
        redirect_to ingredients_path
      else
        render :new
      end
    end
  end

  def edit
    @recipe = Recipe.find(params[:recipe_id])
    @ingredient = Ingredient.find(params[:id])
    render :edit
  end

  def show
    if params[:name_search]
      @recipe = false
      @ingredient = Ingredient.find(params[:id])
      if params[:name_search] != ""
        @search_results = Recipe.search(params[:name_search])
        render :show
      else
        flash[:notice] = "please enter a search query!"
        @search_results = false
        render :show
      end
    elsif params[:recipe_id]
      @recipe = Recipe.find(params[:recipe_id])
      @ingredient = Ingredient.find(params[:id])
      render :show
    elsif params[:id]
      @recipe = false
      @ingredient = Ingredient.find(params[:id])
      render :show
    end
  end

  def update
    @ingredient = Ingredient.find(params[:id])
    if @ingredient.update(ingredient_params)
      flash[:notice] = "ingredient successfully updated!"
      if params[:recipe_id]
        @recipe = Recipe.find(params[:recipe_id].to_i)
        redirect_to recipe_path(@ingredient.recipe)
      else
        redirect_to ingredient_path(@ingredients)
      end
    else
      render :edit
    end
  end

  def destroy
      @ingredient = Ingredient.find(params[:id])
      @ingredient.destroy
      flash[:notice] = "ingredient successfully deleted!"
      if params[:recipe_id]
        @recipe = Recipe.find(params[:recipe_id])
        redirect_to recipe_path(@recipe)
      else
        redirect_to ingredients_path
      end
  end

  private
  def ingredient_params
    params.require(:ingredient).permit(:name)
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @recipes = Recipe.all
    if params[:name_search]
      if params[:name_search] != ""
        @search_results = Recipe.search(params[:name_search])
      else
        flash[:notice] = "please enter a search query!"
        @search_results = false
      end
    end
    render :index
  end

  def new
    @recipe = Recipe.new
    render :new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      flash[:notice] = "recipe successfully added!"
      redirect_to recipes_path
    else
      render :new
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
    render :edit
  end

  def show
    @recipe = Recipe.find(params[:id])
    if params[:ingredient_id]
      puts "hello"
      @ingredient = Ingredient.find(params[:ingredient_id].to_i)
      @recipe.ingredients << @ingredient
    end
    render :show
  end

  def update
    @recipe= Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      flash[:notice] = "recipe successfully updated!"
      redirect_to recipes_path
    else
      render :edit
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    flash[:notice] = "recipe successfully deleted!"
    redirect_to recipes_path
  end

  private
  def recipe_params
    params.require(:recipe).permit(:name, :instructions, :rating, :search)
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.all
    render :index
  end

  def new
    @tag = Tag.new
    render :new
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      flash[:notice] = "tag successfully added!"
      redirect_to tags_path
    else
      render :new
    end
  end

  def edit
    @tag = Tag.find(params[:id])
    render :edit
  end

  def show
    @tag = Tag.find(params[:id])
    render :show
  end

  def update
    @tag= Tag.find(params[:id])
    if @tag.update(tag_params)
      flash[:notice] = "tag successfully updated!"
      redirect_to tags_path
    else
      render :edit
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    flash[:notice] = "tag successfully deleted!"
    redirect_to tags_path
  end

  private
  def tag_params
    params.require(:tag).permit(:category)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ingredients/edit.html.erb
<h1>Edit Ingredient</h1>

<%= render "layouts/ingredient_form" %>

app/views/ingredients/index.html.erb
<h1>Ingredients</h1>
<hr>

<% if @ingredients.any? %>
  <ul>
    <% @ingredients.each do |ingredient| %>
      <li><%= link_to ingredient.name, ingredient_path(ingredient) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no ingredients yet.</p>
<% end %>
<hr>

<p><%= link_to "Create new ingredient", new_ingredient_path %></p>
<p><%= link_to "Recipes", recipes_path %></p>

app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>

<%= render "layouts/ingredient_form" %>

app/views/ingredients/show.html.erb
<h1>Ingredient: <%= @ingredient.name %></h1>


  <% if @ingredient.recipes.any? %>
  <h3>Recipes with this ingredient</h3>
  
    <ul>
    <% @ingredient.recipes.each  do | recipe | %>
      <li>
      <%= link_to recipe.name, recipe_path(recipe)  %>
      </li>
    <% end %>
    </ul>
  <% else %>
    <p>There are no recipes using this ingredient</p>
  <% end %>
<br>
<hr>
<p><%= link_to "Edit ingredient", edit_ingredient_path(@ingredient) %></p>
<p><%= link_to "Delete ingredient", ingredient_path(@ingredient),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>
<p><%= link_to "Return to ingredients", ingredients_path %></p>

<br>
<hr>
<p>Search for a recipe:</p>
<%= form_tag(ingredient_path, method: :get) do %>
  <%= text_field_tag(:name_search, params[:name_search]) %>
  <%= submit_tag ("Search") %>
<% end %>
<% if @search_results %>
  <% if @search_results.any? %>
    <h4>Here are your recipes:</h4>
      <% @search_results.each do |recipe| %>
      <%= form_tag(recipe_path(recipe), method: :get) do %>
      <%= hidden_field_tag("ingredient_id", @ingredient.id) %>
      <%= submit_tag ("#{recipe.name}"), class: 'btn btn-link' %><br>
      <% end %>
  <% end %>
  <% else %>
    <p>No results for this query</p>
<% end %>
<% end %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_ingredient_form.html.erb
<%= render "layouts/errors", :object => @ingredient %>

<%= form_for [@recipe, @ingredient] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <p><%= f.submit %></p>
<% end %>

app/views/layouts/_recipe_form.html.erb
<%= render "layouts/errors", :object => @recipe %>

<%= form_for @recipe do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :instructions %>
  <%= f.text_area :instructions %>
  <%= f.label :rating %>
  <%= f.number_field :rating %>
  <%= f.submit %>
<% end %>

app/views/layouts/_tag_form.html.erb
<%= render "layouts/errors", :object => @tag %>

<%= form_for [@recipe, @tag] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <p><%= f.submit %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipez</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link href="https://fonts.googleapis.com/css2?family=Oswald&family=Pacifico&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= flash[:alert] %>
      <%= flash[:notice] %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>

<%= render "layouts/recipe_form" %>

app/views/recipes/index.html.erb
<div class = "jumbotron">
<h1>Recipes</h1>
</div>

<% if Recipe.five_star.any?%>
<h3> Check out the <em>Top Recipes</em> </h3>
<hr>
  <ul>
    <% Recipe.five_star.each do |recipe| %>
      <li><%= link_to recipe.name, recipe_path(recipe) %></li>
    <% end %>
  </ul>
<% end %>

<% if @recipes.any? %>
<h3>All Recipes</h3>
<hr>
  <ul>
    <% @recipes.each do |recipe| %>
      <li><%= link_to recipe.name, recipe_path(recipe) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no recipes yet.</p>
<% end %>

<br>
<hr>

<p>Search for a recipe:</p>
<%= form_tag(recipes_path, method: :get) do %>
  <%= text_field_tag(:name_search, params[:name_search]) %>
  <%= submit_tag ("Search") %>
<% end %>

<% if @search_results %>
  <% if @search_results.any? %>
    <h4>Here are your recipes:</h4>
    <ul>
      <% @search_results.each do |result| %>
        <li><%= result.name %></li>
      <% end %>
    </ul>
  <% else %>
    <p>No results for this query</p>
  <% end %>
<% end %>

<p><%= link_to "Create new recipe", new_recipe_path %></p>

<p><%= link_to "Check out all the ingredients", ingredients_path %></p>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render "layouts/recipe_form" %>

app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>
<hr>
<h3>Rating: <%= @recipe.rating %></h3>

<% if @recipe.ingredients.any? %>
  <h4>Here are the ingredients for this recipe:</h4>
<hr>
  <% @recipe.ingredients.each do |ingredient| %>
    <ul>
      <li>
        <%= link_to ingredient.name, recipe_ingredient_path(@recipe, ingredient) %>
      </li>
    </ul>
  <% end %>
<% else %>
  <p>No ingredients are listed for this recipe.</p>
<% end %>
<hr>
<br>
<p><%= link_to "Add a ingredient", new_recipe_ingredient_path(@recipe) %></p>

<p><%= link_to "Edit", edit_recipe_path(@recipe) %></p>
<p><%= link_to "Delete", recipe_path(@recipe),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>

<p><%= link_to "Return to recipes", recipes_path %></p>

app/views/tags/edit.html.erb
<h1>Edit Tag</h1>

<%= render "layouts/tag_form" %>

app/views/tags/index.html.erb
<h1>Tags</h1>

<% if @tags.any? %>
  <ul>
    <% @tags.each do |tag| %>
      <li><%= link_to tag.name, tag_path(tag) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no tags yet.</p>
<% end %>


<p><%= link_to "Create new tag", new_tag_path %></p>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render "layouts/tag_form" %>

app/views/tags/show.html.erb
<h1>Tag: <%= @tag.category %></h1>
<h2>Recipe: <%= @recipe.name %></h2>
<h3><%= @tag.category %></h3>

<p><%= link_to "Edit tag", edit_recipe_tag_path(@recipe, @tag) %></p>
<p><%= link_to "Delete tag", recipe_tag_path(@recipe, @tag),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to recipe", recipe_path(@recipe) %></p>